# Generated by Django 4.1.10 on 2024-11-06 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmasikCalismaClickRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('module', models.CharField(max_length=100)),
                ('video_1_clicks', models.IntegerField(default=0)),
                ('video_2_clicks', models.IntegerField(default=0)),
                ('video_3_clicks', models.IntegerField(default=0)),
                ('click_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.videofile')),
            ],
        ),
    ]
