# Generated by Django 4.1.10 on 2024-11-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_karmasikcalismaclickrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karmasikcalismaclickrecord',
            name='video_file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.videofile'),
        ),
    ]
