# Generated by Django 4.1.10 on 2024-11-06 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_remove_isitselzeminaudiorecord_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isitselzeminaudiorecord',
            name='ses1',
            field=models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/'),
        ),
        migrations.AlterField(
            model_name='isitselzeminaudiorecord',
            name='ses10',
            field=models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/'),
        ),
        migrations.AlterField(
            model_name='isitselzeminaudiorecord',
            name='ses2',
            field=models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/'),
        ),
        migrations.AlterField(
            model_name='isitselzeminaudiorecord',
            name='ses3',
            field=models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/'),
        ),
        migrations.AlterField(
            model_name='isitselzeminaudiorecord',
            name='ses4',
            field=models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/'),
        ),
        migrations.AlterField(
            model_name='isitselzeminaudiorecord',
            name='ses5',
            field=models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/'),
        ),
        migrations.AlterField(
            model_name='isitselzeminaudiorecord',
            name='ses6',
            field=models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/'),
        ),
        migrations.AlterField(
            model_name='isitselzeminaudiorecord',
            name='ses7',
            field=models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/'),
        ),
        migrations.AlterField(
            model_name='isitselzeminaudiorecord',
            name='ses8',
            field=models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/'),
        ),
        migrations.AlterField(
            model_name='isitselzeminaudiorecord',
            name='ses9',
            field=models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/'),
        ),
        migrations.CreateModel(
            name='IsitselBellekAudioRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('module_name', models.CharField(max_length=100)),
                ('ses1', models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/')),
                ('ses2', models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/')),
                ('ses3', models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/')),
                ('ses4', models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/')),
                ('ses5', models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/')),
                ('ses6', models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/')),
                ('ses7', models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/')),
                ('ses8', models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/')),
                ('ses9', models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/')),
                ('ses10', models.FileField(blank=True, null=True, upload_to='isitsel_bellek_audio_records/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
