# Generated by Django 4.1.10 on 2024-11-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_verbalmemoryrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickrecord',
            name='video_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
