# Generated by Django 4.1.10 on 2024-11-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_clickrecord_video_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickrecord',
            name='video_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
